"""The demo estate has to be a coherent story, not just plausible numbers.

Every rule in this scanner is exercised against this data, every screenshot
comes from it, and it is what a reviewer looks at first. So its internal
consistency is a product property, not a fixture detail — and it was genuinely
broken. History was generated by re-running the generator at a worse defect
ratio, which produces an org that *resembles* the real one rather than being it:
seventeen components appeared in one org's newest scan that had never existed in
the scan before it, while its score improved. Field counts went 57, 54, 57.

That is not cosmetic. Survival counts how many consecutive scans reported the
same defect, and over a re-rolled history a finding "surviving" is partly the
RNG landing the same way twice — the number measured coincidence as much as
neglect. These tests are what stop that returning.
"""

import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scanner"))

import pytest                                                  # noqa: E402
import scan_portfolio                                          # noqa: E402

DIMENSIONS = ("D1", "D2", "D3", "D4", "D5")


@pytest.fixture(scope="module")
def portfolio():
    scans, _orgs = scan_portfolio.build_portfolio()
    return scans


@pytest.fixture(scope="module")
def histories(portfolio):
    """Orgs that carry more than one scan, oldest first."""
    by_org = defaultdict(list)
    for s in portfolio:
        by_org[s["scan"]["target_org"]].append(s)
    return {org: sorted(ss, key=lambda s: s["scan"]["scan_timestamp"])
            for org, ss in by_org.items() if len(ss) > 1}


def components(scan):
    return {f["component_api_name"] for f in scan["findings"]
            if "." in f["component_api_name"]}


def test_the_demo_actually_has_a_history_to_check():
    """Guards every other test in this file: if the generator stops producing
    history, they would all pass by having nothing to look at."""
    scans, _ = scan_portfolio.build_portfolio()
    by_org = defaultdict(int)
    for s in scans:
        by_org[s["scan"]["target_org"]] += 1
    assert sum(1 for n in by_org.values() if n > 1) >= 2


# ------------------------------------------------- the same org, over time

def test_no_component_appears_in_a_later_scan_of_the_same_org(histories):
    """A field that did not exist in April cannot be the subject of a finding in
    July while the org's score improves. This is the check that failed at 17
    components and is the reason history is derived from the present rather than
    re-rolled."""
    for org, scans in histories.items():
        for older, newer in zip(scans, scans[1:]):
            appeared = components(newer) - components(older)
            assert not appeared, (
                f"{org}: {len(appeared)} component(s) in {newer['scan']['scan_timestamp'][:10]} "
                f"that its own previous scan never saw — e.g. {sorted(appeared)[:3]}")


def test_an_org_never_gains_fields_going_forward(histories):
    """Remediation retires fields; it does not create them. A count that rises
    and falls is noise wearing the shape of a burn-down."""
    for org, scans in histories.items():
        counts = [s["scan"]["components_scanned"] for s in scans]
        assert counts == sorted(counts, reverse=True), f"{org}: {counts}"


def test_readiness_improves_over_time(histories):
    for org, scans in histories.items():
        scores = [s["scan"]["composite_score"] for s in scans]
        assert scores == sorted(scores), f"{org}: {scores}"


def test_every_dimension_burns_down_rather_than_wobbling(histories):
    """A dimension that loses a finding and gets it back is a persona losing a
    grant and regaining it, or a report that stopped and restarted — neither is
    something an org does, and both hid a re-roll."""
    for org, scans in histories.items():
        for dim in DIMENSIONS:
            counts = [sum(1 for f in s["findings"] if f["dimension"] == dim) for s in scans]
            assert counts == sorted(counts, reverse=True), f"{org} {dim}: {counts}"


def test_survival_counts_reflect_a_real_run(histories):
    """The consequence of everything above. A finding present in every scan of
    an org must carry a survival count equal to that org's number of scans — if
    the history churns, the run resets and the count silently understates."""
    for org, scans in histories.items():
        oldest = {(f["rule_id"], f["component_api_name"]) for f in scans[0]["findings"]}
        newest = {(f["rule_id"], f["component_api_name"]): f for f in scans[-1]["findings"]}
        throughout = [newest[k] for k in newest if k in oldest]
        assert throughout, f"{org}: nothing survived the whole history"
        assert any(f.get("survived_scans") == len(scans) for f in throughout), (
            f"{org}: no finding reached a run of {len(scans)}, so the history is "
            f"not being read as one org")


# ------------------------------------------------------------- every org

def test_every_org_has_more_than_one_persona(portfolio):
    """An org with a single blanket permission set and no profiles reads as a
    broken parse. An acquired instance on an unrelated schema has none of the
    parent's roles — it has its own, and is generated with them."""
    for s in portfolio:
        assert len(s["personas"]) > 1, (
            f"{s['scan']['target_org']}: {[p['name'] for p in s['personas']]}")


def test_semantic_density_is_a_share(portfolio):
    """0.0 is a legitimate measurement, not a missing one — an org where nothing
    survives with an informative description genuinely scores zero, and the
    schema stores it as zero rather than null so the dashboard can say so."""
    for s in portfolio:
        d = s["scan"]["semantic_density"]
        assert 0 <= d <= 1, f"{s['scan']['target_org']}: {d}"


def test_semantic_density_actually_separates_good_orgs_from_bad(portfolio):
    """A metric on the dashboard's front page has to move with the thing it
    claims to measure. It did not: the degradation model left even the worst
    possible org with 43% of its descriptions intact, so density sat between
    0.67 and 0.83 across a corpus whose scores ran from 21 to 95 — present,
    plausible, and carrying no information."""
    latest = {}
    for s in portfolio:
        org = s["scan"]["target_org"]
        if org not in latest or s["scan"]["scan_timestamp"] > latest[org]["scan"]["scan_timestamp"]:
            latest[org] = s
    rows = sorted(((s["scan"]["composite_score"], s["scan"]["semantic_density"])
                   for s in latest.values()))
    half = len(rows) // 2
    worst = sorted(d for _, d in rows[:half])
    best = sorted(d for _, d in rows[half:])
    median = lambda v: v[len(v) // 2]                          # noqa: E731
    assert median(best) > median(worst), (
        f"density does not separate: worst half median {median(worst):.2f}, "
        f"best half median {median(best):.2f}")


def test_no_finding_names_a_field_the_org_cannot_change(portfolio):
    """Portfolio-level guard on the managed-package rule: a ticket nobody can
    close is worse than no ticket, and this is where 86 of them once shipped."""
    import orgiq_spike as scanner
    bad = [f["component_api_name"] for s in portfolio for f in s["findings"]
           if scanner._MANAGED.match(f["component_api_name"].split(".")[-1])]
    assert not bad, f"findings on managed-package fields: {sorted(set(bad))[:5]}"


def test_drift_never_penalises_a_dimension_score(portfolio):
    """Drift is an estate-level observation, not a defect in the org it names,
    so it is reported under its own dimension and must never be counted in
    D1–D5."""
    drift = [f for s in portfolio for f in s["findings"] if f["dimension"] == "Drift"]
    assert drift, "no drift findings at all — the estate check stopped running"
    assert all(f["dimension"] not in DIMENSIONS for f in drift)
